version: '3'
#networks:
#  automation:
#    driver: bridge
services:
  ansible-tower:
    build:
      context: ./ansible-tower
    container_name: ansible-tower
#    healthcheck:
#      interval: 4m
#      retry: 4
#      test: ["CMD", "curl", "-f", "http://localhost"]
#      timeout: 1m
    hostname: ansible-tower
    image: ansible-tower:0.1
    ports:
      - "7122:22/tcp"
    restart: always
    stop_grace_period: 1m
