# Supported Operating System, as described in Ansible Tower's official docs:
#   http://docs.ansible.com/ansible-tower/latest/html/quickinstall/prepare.html#prerequisites-and-requirements
FROM centos:7.2.1511

