version: '2'
services:
  ansible-core:
    build:
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
      context: ./ansible-core
      dockerfile: Dockerfile
    container_name: ansible-core
    hostname: ansible-core
    image: automation-labs/ansible:1.0
    links:
      - node-01
      - node-02
      - node-03
      - node-04
    ports:
      - 7022:22/tcp
    volumes:
      - ./ansible-core/volumes/etc-ansible:/etc/ansible
#  gitlab:
#    container_name: gitlab
#    hostname: gitlab
#    image: gitlab/gitlab-ce:latest
#    ports:
#      - 8022:22/tcp
#      - 80:80/tcp
#      - 443:443/tcp
#    volumes:
#      - ./gitlab/volumes/config:/etc/gitlab
#  jenkins:
#    container_name: jenkins
#    hostname: jenkins
#    image: "jenkins:2.60.1-alpine"
#    ports:
#      - "8082:8080"
#    links:
#      - ansible-core
  node-01:
    container_name: node-01
    hostname: node-01
    image: automation-labs/ansible:1.0
    ports:
      - 7122:22/tcp
  node-02:
    container_name: node-02
    hostname: node-02
    image: automation-labs/ansible:1.0
    ports:
      - 7222:22/tcp
  node-03:
    container_name: node-03
    hostname: node-03
    image: automation-labs/ansible:1.0
    ports:
      - 7322:22/tcp
  node-04:
    container_name: node-04
    hostname: node-04
    image: automation-labs/ansible:1.0
    ports:
      - 7422:22/tcp
  rundeck:
    build:
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
      context: ./rundeck-ansible
      dockerfile: Dockerfile
    container_name: rundeck
    environment:
    - "SERVER_URL=http://localhost:4440"
    - "EXTERNAL_SERVER_URL=http://${sysExternalIP}:8081"
    - "RD_URL=http://localhost:4440"
    - "RD_BYPASS_URL=http://${sysExternalIP}:8081"
    - "RD_USER=admin"
    - "RD_PASSWORD=admin"
    - "RD_PROJECT=ansible-lab"
    hostname: rundeck
    image: automation-labs/rundeck-ansible:1.0
    links:
      - ansible-core
    ports:
      - 8081:4440/tcp
    volumes:
      - ./rundeck-ansible/volumes/rundeck-etc:/etc/rundeck
      - ./rundeck-ansible/volumes/rundeck-jobs:/etc/rundeck-jobs
      - ./rundeck-ansible/volumes/rundeck-ssh:/var/lib/rundeck/.ssh
      - ./rundeck-ansible/volumes/rundeck-var:/var/rundeck
