version: '2'
services:
  ansible-core-01:
    build:
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
      context: ./ansible
      dockerfile: Dockerfile
    container_name: ansible-core-01
    hostname: ansible-core-01
    image: automation-lab/ansible:1.0
    links:
      - gitlab
      - node-01
      - node-02
      - node-03
      - node-04
  ansible-core-02:
    container_name: ansible-core-02
    hostname: ansible-core-02
    image: automation-lab/ansible:1.0
    links:
      - gitlab
      - node-01
      - node-02
      - node-03
      - node-04
  ansible-core-03:
    container_name: ansible-core-03
    hostname: ansible-core-03
    image: automation-lab/ansible:1.0
    links:
      - gitlab
      - node-01
      - node-02
      - node-03
  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    image: elasticsearch:5.5.0
    volumes:
      - ./elasticsearch/volumes/config:/usr/share/elasticsearch/config
  gitlab:
    container_name: gitlab
    environment:
      - "GITLAB_OMNIBUS_CONFIG=external_url 'http://${usrExternalIP}/';"
      - "GITLAB_ROOT_PASSWORD=automation"
    hostname: gitlab
    image: gitlab/gitlab-ce:9.4.3-ce.0
    ports:
      - 80:80/tcp
    volumes:
      - ./gitlab/volumes/config:/etc/gitlab
  logstash:
    command: -f /etc/logstash/conf.d/logstash.conf
    container_name: logstash
    hostname: logstash
    image: logstash:5.5.0
    links:
      - elasticsearch
    volumes:
      - ./logstash/volumes/config:/etc/logstash/conf.d
  node-01:
    container_name: node-01
    hostname: node-01
    image: automation-lab/ansible:1.0
  node-02:
    container_name: node-02
    hostname: node-02
    image: automation-lab/ansible:1.0
  node-03:
    container_name: node-03
    hostname: node-03
    image: automation-lab/ansible:1.0
  node-04:
    container_name: node-04
    hostname: node-04
    image: automation-lab/ansible:1.0
  rundeck:
    build:
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
      context: ./rundeck
      dockerfile: Dockerfile
    container_name: rundeck
    environment:
    - "SERVER_URL=http://localhost:4440"
    - "EXTERNAL_SERVER_URL=http://${usrExternalIP}:8080"
    - "RD_URL=http://localhost:4440"
    - "RD_BYPASS_URL=http://${usrExternalIP}:8080"
    - "RD_USER=admin"
    - "RD_PASSWORD=admin"
    - "RD_PROJECT=ansible-lab"
    hostname: rundeck
    image: automation-lab/rundeck:1.0
    links:
      - ansible-core-01
      - ansible-core-02
      - ansible-core-03
      - gitlab
      - logstash
    ports:
      - 8080:4440/tcp
    volumes:
      - ./rundeck/volumes/rundeck-etc:/etc/rundeck
      - ./rundeck/volumes/rundeck-jobs:/etc/rundeck-jobs
      - ./rundeck/volumes/rundeck-var:/var/rundeck
