- description: Executes an Ansible Playbook
  executionEnabled: true
  id: 7ac894bd-3629-49e1-94cb-4dd449f7f050
  loglevel: INFO
  name: Ansible Playbook
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      threadcount: 1
    filter: ansible-core
  nodesSelectedByDefault: true
  schedule:
    dayofmonth:
      day: '*'
    month: '*'
    time:
      hour: '*'
      minute: '*'
      seconds: '0'
    year: '*'
  scheduleEnabled: true
  sequence:
    commands:
    - description: Executing an Ansible Playbook
      exec: /usr/bin/ansible-playbook /etc/ansible/apache.yml
    keepgoing: false
    strategy: node-first
  uuid: 7ac894bd-3629-49e1-94cb-4dd449f7f050
