- description: Saying Hello to the World!
  executionEnabled: true
  group: Initial Pack
  loglevel: INFO
  name: Hello World
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      threadcount: 1
    filter: 'tags: ansible'
  nodesSelectedByDefault: true
  scheduleEnabled: true
  sequence:
    commands:
    - description: Saying Hello
      exec: echo "Ansible Core says Hello World!"
    keepgoing: false
    strategy: node-first
