- description: Update Ansible's Playbooks and Roles
  executionEnabled: true
  group: Initial Pack
  id: b8d0bc47-899b-4e97-be93-846c84c406d3
  loglevel: INFO
  name: Update - Ansible
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      threadcount: 1
    filter: 'tags: ansible'
  nodesSelectedByDefault: true
  scheduleEnabled: true
  sequence:
    commands:
    - description: Updating Ansible's Playbooks and Roles
      script: |-
        #!/bin/bash
        gitRepository="http://gitlab/root/ansible-lab.git"
        gitClonePath="${HOME}/ansible-lab"
        jobProject="ansible-lab"
        jobFormat="yaml"
        jobDuplicate="update"

        ## This script will 'auto-update' Ansible's Repository

        if [ -d ${gitClonePath} ]; then
          echo "Git - Repository found - Pulling for changes"
          cd ${gitClonePath} && git pull
        else
          echo "Git - Repository not found - Cloning"
          git clone ${gitRepository} ${gitClonePath}
        fi
    keepgoing: false
    strategy: node-first
  uuid: b8d0bc47-899b-4e97-be93-846c84c406d3
