- description: 'Hello World!'
  executionEnabled: true
  id: 1f82db91-6d3b-4905-a7dc-4c41dba05aff
  loglevel: DEBUG
  name: Hello World
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      threadcount: 1
    filter: .*
  nodesSelectedByDefault: true
  options:
  - description: What to say?
    name: optstring
    required: true
    value: hello-world
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        #!/bin/bash

        echo "The string is => $RD_OPTION_OPTSTRING"
    keepgoing: false
    strategy: node-first
  uuid: 1f82db91-6d3b-4905-a7dc-4c41dba05aff
