- description: 'The best!'
  executionEnabled: true
  loglevel: DEBUG
  name: My Favorite Role
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      threadcount: 1
    filter: .*
  nodesSelectedByDefault: true
  options:
  - description: What to say?
    name: optstring
    required: true
    value: my-favorite-role
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        #!/bin/bash

        echo "The string is => $RD_OPTION_OPTSTRING"
    keepgoing: false
    strategy: node-first
